create table user_details (
user_id varchar(10) not null,
user_name varchar(50) not null,
user_type varchar(10) not null,
user_pwd varchar(8) not null,
roll_no int not null,
books_borrowed int default=0,
primary key(user_id)
);

insert into user_details values
('ladmin','Librarian (ADMIN)','admin','psbbadmin@2023',0);

create table author_master (
AuthorID int primary key not null,
AuthorName varchar(50) not null
);

insert into author_master
values
(1,'Mark Twain'),
(2,'Lewis Carrol'),
(3,'Coleridge'),
(4,'George Orwell'),
(5,'G.B.Shaw'),
(6,'Lewis Wallace'),
(7,'Jules Verne'),
(8,'Babur'),
(9,'Leo Tolstoy'),
(10,'Kautilya'),
(11,'Jane Austen'),
(12,'Bankimchandra Chattopadhyay'),
(13,'Jean Jacques Rousseau'),
(14,'Adolf Hitler'),
(15,'Jonathan Swift'),
(16,'Oliver Goldsmith'),
(17,'D.P. Moynihan'),
(18,'Edward Gibbon'),
(19,'H.G. Wells'),
(20,'Sir Walter Scott'),
(21,'E.M.Forster'),
(22,'Arthur Conan Doyle'),
(23,'Somerset Maughan'),
(24,'Kalidas'),
(25,'Thomas Hardy'),
(26,'Pandit Jawaharlal Nehru'),
(27,'John Bunyan'),
(28,'Mahatma M.K.Gandhi'),
(29,'Shakespeare'),
(30,'Charles Dickens'),
(31,'Rabindra Nath Tagore'),
(32,'Alexander Solzhenitsyn'),
(33,'Sir Thomas Moor'),
(34,'Charles Darwin'),
(35,'Dostoevsky'),
(36,'Karl Marx'),
(38,'Alexander Dumas'),
(39,'Chaucer'),
(40,'Dante'),
(41,'Louis Gluck'),
(42,'JK Rowling'),
(43,'Robert Ludlum');

create table book_master (
bookID int primary key not null,
bookName varchar(100) not null,
AuthorID int not null,
availability char(1) default 'y',
foreign key (AuthorID) references author_master(AuthorID) on update cascade on delete cascade
);

insert into book_master 
values
(1,'Adventures of Tom Sawyer',1,'y'),
(2,'Alice in Wonderland',2,'y'),
(3,'Ancient Mariner',3,'y'),
(4,'Animal Farm',4,'y'),
(5,'Arms and the Man',5,'y'),
(6,'Ben Hur',6,'y'),
(7,'Around the World in eighty days',7,'y'),
(8,'Baburnama',8,'y'),
(9,'Anna Karenina',9,'y'),
(10,'Arthashastra',10,'y'),
(11,'Pride and Prejudice',11,'y'),
(12,'Anand Math',12,'y'),
(13,'Le Contract Social',13,'y'),
(14,'Mein Kampf',14,'y'),
(15,'Gulliver\'s Travels',15,'y'),
(16,'The Vicar of Wakefield',16,'y'),
(17,'A Dangerous place',17,'y'),
(18,'The Decline and Fall of the Roman Empire',18,'y'),
(19,'Time Machine',19,'y'),
(20,'The Lady of the Last Minstrel',20,'y'),
(21,'A passage to India',21,'y'),
(22,'Adventures of Sherlock Holmes',22,'y'),
(23,'The Moon and Sixpence',23,'y'),
(24,'Raghuvamsa',24,'y'),
(25,'Avigyan Sakuntalam',24,'y'),
(26,'Shakuntala',24,'y'),
(27,'Far from the Madding Crowd',25,'y'),
(28,'Discovery of India',26,'y'),
(29,'Pilgrim\'s Progress',27,'y'),
(30,'My Experiments with Truth',28,'y'),
(31,'The Merchant of Venice',29,'y'),
(32,'Antony and Cleopatra',29,'y'),
(33,'A Tale of Two Cities',30,'y'),
(34,'David Copperfield',30,'y'),
(35,'Geetanjali',31,'y'),
(36,'One Day in the Life of Ivan Denisovich',32,'y'),
(37,'Utopia',33,'y'),
(38,'Origin of Species',34,'y'),
(39,'Crime and Punishment',35,'y'),
(40,'Das Kapital ',36,'y'),
(41,'Chitra',31,'y'),
(42,'Count of Monte Cristo',37,'y'),
(43,'Bisarjan',31,'y'),
(44,'Canterbury Tales',38,'y'),
(45,'Divine Comedy',39,'y'),
(46,'The Wild Iris',40,'y'),
(47,'Harry Potter and The Sorceror\'s stone',41,'y'),
(48,'Harry Potter and The Chamber of Secrets',41,'y'),
(49,'Harry Potter and The Prisoner of Azkaban',41,'y'),
(50,'Harry Potter and The Half blood Prince',41,'y'),
(51,'Harry Potter and The Goblet of Fire',41,'y'),
(52,'Harry Potter and The Deathly Hallows-1',41,'y'),
(53,'Harry Potter and The Deathly Hallows-2',41,'y'),
(54,'Harry Potter and The Cursed Child',41,'y'),
(55,'The Bourne Identity',42,'y'),
(56,'The Bourne Supremacy',42,'y'),
(57,'The Bourne Ultimatum',42,'y');


